#!/bin/bash

### Use PKG_DIR as working directory.
PKG_DIR=/tmp/_pkg_dir_
rm -rf $PKG_DIR
mkdir -p $PKG_DIR

### Copy Package Center scripts to PKG_DIR
cp -av scripts $PKG_DIR/

### Create package dirs
mkdir -p $PKG_DIR/target

### Copy JRE to target
cp -r build/* $PKG_DIR/target/

### get spk packing functions
source /pkgscripts/include/pkg_util.sh

create_package_tgz() {
	local firmwere_version=
	local package_tgz_dir=/tmp/_package_tgz
	local binary_dir=$package_tgz_dir/bin

	### clear destination directory
	rm -rf $package_tgz_dir && mkdir -p $package_tgz_dir

	### install needed file into PKG_DIR
	mkdir -p $binary_dir
	mkdir -p $package_tgz_dir/lib
	cp -r $PKG_DIR/target/* $package_tgz_dir/lib

	### create package.tgz $1: source_dir $2: dest_dir
	pkg_make_package $package_tgz_dir "${PKG_DIR}"
}

create_spk(){
	cp -av scripts $PKG_DIR/scripts
	cp -av PACKAGE_ICON*.PNG $PKG_DIR
	cp -av conf $PKG_DIR
	#cp -av LICENSE $PKG_DIR

	./INFO.sh > INFO
	cp INFO $PKG_DIR/INFO

	### Create the final spk.
	# pkg_make_spk <source path> <dest path> <spk file name>
	# Please put the result spk into /image/packages
	# spk name functions: pkg_get_spk_name pkg_get_spk_unified_name pkg_get_spk_family_name
	mkdir -p /image/packages
	pkg_make_spk ${PKG_DIR} "/image/packages" $(pkg_get_spk_family_name)
}

main() {
	create_package_tgz
	create_spk
}

main "$@"
