#!/bin/bash

case $1 in
	start)
		exit 0
		;;
	stop)
		exit 0
		;;
	status)
		exit 0
		;;
	*)
		exit 1
		;;
esac
#!/bin/sh

# Package
PACKAGE="AdvancedFileServer"
DNAME="Advanced File Server"

# Others
INSTALL_DIR="/var/packages/${PACKAGE}/target"
JAR_FILE="${INSTALL_DIR}/lib/afs-srv.jar"
JRE_PATH="${INSTALL_DIR}/jre"
PID_FILE="/var/run/${PACKAGE}.pid"

start_daemon() {
    if [ -f ${PID_FILE} ] && kill -0 $(cat ${PID_FILE}) > /dev/null 2>&1; then
        return 0
    fi
    
    # Use bundled JRE
    ${JRE_PATH}/bin/java \
        -Duser.home=${INSTALL_DIR} \
        -jar ${JAR_FILE} > /dev/null 2>&1 &
    echo $! > ${PID_FILE}
}

stop_daemon() {
    if [ -f ${PID_FILE} ] && kill -0 $(cat ${PID_FILE}) > /dev/null 2>&1; then
        kill $(cat ${PID_FILE})
        rm -f ${PID_FILE}
    fi
}

daemon_status() {
    if [ -f ${PID_FILE} ] && kill -0 $(cat ${PID_FILE}) > /dev/null 2>&1; then
        return 0
    fi
    return 1
}

case $1 in
    start)
        if daemon_status; then
            echo ${DNAME} is already running
            exit 0
        else
            echo Starting ${DNAME} ...
            start_daemon
            exit $?
        fi
        ;;
    stop)
        if daemon_status; then
            echo Stopping ${DNAME} ...
            stop_daemon
            exit $?
        else
            echo ${DNAME} is not running
            exit 0
        fi
        ;;
    status)
        if daemon_status; then
            echo ${DNAME} is running
            exit 0
        else
            echo ${DNAME} is not running
            exit 1
        fi
        ;;
    *)
        exit 1
        ;;
esac
